### ISSUE TITLE
Question: bottom button fly-in at same time?

### ISSUE THREAD

**Issue by samumist** [mike-st/adapt-carousel-menu#3]
Hello @mike-st 
Just noticed that in desktop view, starting from second bottom button, when you click the navigation arrow, the bottom button flying in all together rather than a fade-in transition effect as for the first button.
![carousel-menu](https://cloud.githubusercontent.com/assets/3883086/19878562/28c8ec9c-a025-11e6-9c3b-b60208046257.gif)

I'm wondering if this is intentional?

**Comment by mike-st** [comment]
Hi yes this was intentional. I wanted to make the movement left or right be really noticed by the end-user to know that the slides are changing in case the same image is used. This is similar to a Carousel kind of feel. That said it is turned off on the navigation buttons on the bottom when they are clicked as I felt they worked better and less confusing as a static state. Please feel free to change this motion if you desire of course..

**Comment by samumist** [comment]
Cool, thanks for the explanation.
